{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ethyca.janussdk",
    "module": "android",
    "version": "1.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "android-1.0.21.aar",
          "url": "android-1.0.21.aar",
          "size": 310899,
          "sha512": "d7519cf66aa8af3c9aee5c29ef730a62b9eec3c57480f0b0ef0d8b0d8ce83596b87fa26ddb50be559be2a74104fa59ab3f70c53a7f0ab7df42b6f9f94042f425",
          "sha256": "a553c25719e3b241976a90875758a0192cd4d7b3a7fe9a801aa839c23361f765",
          "sha1": "8fd97636663da59834ccbc5f0460215337994fa6",
          "md5": "815965b3d07a1c36b256dc4fc84d4dbd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "android-1.0.21.aar",
          "url": "android-1.0.21.aar",
          "size": 310899,
          "sha512": "d7519cf66aa8af3c9aee5c29ef730a62b9eec3c57480f0b0ef0d8b0d8ce83596b87fa26ddb50be559be2a74104fa59ab3f70c53a7f0ab7df42b6f9f94042f425",
          "sha256": "a553c25719e3b241976a90875758a0192cd4d7b3a7fe9a801aa839c23361f765",
          "sha1": "8fd97636663da59834ccbc5f0460215337994fa6",
          "md5": "815965b3d07a1c36b256dc4fc84d4dbd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-1.0.21-sources.jar",
          "url": "android-1.0.21-sources.jar",
          "size": 86988,
          "sha512": "2ae59f3358c7ed964482cb9e91bd868b67f1be2e4104147fd48900f8b26b03f0aec2c7340e11dcb21cb2e5610d793eca299d5915da108586d8e824e17be4d687",
          "sha256": "63646ea9dda429ea322726bdb64a4911b3a9142d44bcf796236a72f8d62a675d",
          "sha1": "f0e93fd126223ae1f5355ac113c4ee263f319265",
          "md5": "ab04e3f26f07a880b9ab5e3f24548953"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-1.0.21-javadoc.jar",
          "url": "android-1.0.21-javadoc.jar",
          "size": 991429,
          "sha512": "4ab8dd6ff0881cf85e57f6bd4277faeffe386b9911b2423dc2df071d08cedb48603a0f76b80deeabf2dd69da93e0a81b95575679dd0aae3a3933609945e405a4",
          "sha256": "8f0386035a16038ecd6f1163f8f47e8abb1dd9c38dcb0cceef0cc5e91d973041",
          "sha1": "e8170c9e4369210207f239ddfec9238d57c8b944",
          "md5": "9ff93c3df7b108294d44c9bdd88618b9"
        }
      ]
    }
  ]
}
