{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ethyca.janussdk",
    "module": "android",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "android-1.1.0.aar",
          "url": "android-1.1.0.aar",
          "size": 329351,
          "sha512": "52a2a239a8c9952d7eb18feeece5b7d8945496d22a20306b01f17e9ea72a9fde79eba714fce256815c0c247c66bcd09c1ada379043b897c6410ec0958a78869d",
          "sha256": "709bf9963ea364b49ddec0110e6faed7d0c34430fb440d144fbe99da8098f398",
          "sha1": "d2de8ae5084c0a1b2b92d5c55da259247e7bf6da",
          "md5": "98d2514bdee93c510fe6d1390c795c43"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "android-1.1.0.aar",
          "url": "android-1.1.0.aar",
          "size": 329351,
          "sha512": "52a2a239a8c9952d7eb18feeece5b7d8945496d22a20306b01f17e9ea72a9fde79eba714fce256815c0c247c66bcd09c1ada379043b897c6410ec0958a78869d",
          "sha256": "709bf9963ea364b49ddec0110e6faed7d0c34430fb440d144fbe99da8098f398",
          "sha1": "d2de8ae5084c0a1b2b92d5c55da259247e7bf6da",
          "md5": "98d2514bdee93c510fe6d1390c795c43"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-1.1.0-sources.jar",
          "url": "android-1.1.0-sources.jar",
          "size": 97856,
          "sha512": "b6c978860f06d471d58425154b5981218ee64939bca147216f4d20be47ca6e314ec9022cdf5f0e6de9c487965b7baf01bca8545401a2fc83d9b9e618991c2f96",
          "sha256": "d9b8fbee0c5016e0859844eb22e5728758ab5a089ce7e6d80f7e11c8d27609e4",
          "sha1": "3c96987caa147e121012ce6426f4efe8ee046423",
          "md5": "07c2f68f9849d05b731d0a1cdaee0e73"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-1.1.0-javadoc.jar",
          "url": "android-1.1.0-javadoc.jar",
          "size": 1007712,
          "sha512": "fe0a1cc9685e2a997bf643feb12a44abb2626a9dcd6bee4688d2acc8ece4549eec32b164ea83506992461176dae18facef4700544c82e5444fde77230b512046",
          "sha256": "18e5224e25dfefc35d415df83718fac71e3f6beba8eb40b1b8ed3ac3946d3b54",
          "sha1": "5e586b44d2b73ed2cfe6b4cedb82c8ebdf348a91",
          "md5": "0f2a5886e47516f09415d4d4f759aade"
        }
      ]
    }
  ]
}
